-- Crear tabla formularios
DROP TABLE IF EXISTS formularios;
CREATE TABLE formularios (
    ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    MENSAJE VARCHAR(255) NOT NULL, 
    PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS USERS;

CREATE TABLE  "USERS" (
    "USER_ID" NUMBER NOT NULL,
	"USERNAME" VARCHAR2(255) NOT NULL PRIMARY KEY,
	"EMAIL" VARCHAR2(255) NOT NULL,
    "PASSWORD" VARCHAR2(255) NOT NULL
    
);

DROP TABLE IF EXISTS MOVIELISTS;

CREATE TABLE  "MOVIELISTS" (
    "MOVIELISTNAME" VARCHAR2(255) NOT NULL,
    "USERNAME" VARCHAR2(255) NOT NULL,
    "MOVIELIST_ID" VARCHAR2(20) NOT NULL PRIMARY KEY
    
);

DROP TABLE IF EXISTS PELICULAS; 

CREATE TABLE "PELICULAS" (
    "ID" NUMBER PRIMARY KEY NOT NULL, 
    "NOMBRE" VARCHAR(255) NOT NULL, 
    "YEAR" NUMBER NOT NULL, 
    "CATEGORIA" VARCHAR(255) NOT NULL, 
    "URL" VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS MOVIELISTS_PELICULAS;

CREATE TABLE "MOVIELISTS_PELICULAS"(
    "ID_MOVIELIST" VARCHAR(20) NOT NULL,
    "ID_PELICULA" INTEGER NOT NULL
);