DROP TABLE IF EXISTS PELICULAS; 

CREATE TABLE "PELICULAS" (
    "ID" NUMBER PRIMARY KEY NOT NULL, 
    "NOMBRE" VARCHAR(255) NOT NULL, 
    "YEAR" NUMBER NOT NULL, 
    "CATEGORIA" VARCHAR(255) NOT NULL, 
    "URL" VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS FORMULARIOS; 

CREATE TABLE "FORMULARIOS" (
    "ID" NUMBER  PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    "NOMBRE" VARCHAR(50) NOT NULL, 
    "CORREO" VARCHAR(80) NOT NULL, 
    "MENSAJE" VARCHAR(255) NOT NULL
);