-- Crear tabla DEMO
/*DROP TABLE IF EXISTS DEMO;
CREATE TABLE DEMO (
    ID INT NOT NULL AUTO_INCREMENT,
    KEY_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
*/

-- Crear tabla formularios
DROP TABLE IF EXISTS formularios;
CREATE TABLE formularios (
    ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    MENSAJE VARCHAR(255) NOT NULL, 
    PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS USERS;

CREATE TABLE  "USERS" (
    "USER_ID" NUMBER NOT NULL,
	"USERNAME" VARCHAR2(255) NOT NULL PRIMARY KEY,
	"EMAIL" VARCHAR2(255) NOT NULL,
    "PASSWORD" VARCHAR2(255) NOT NULL
    
);

DROP TABLE IF EXISTS MOVIELISTS;

CREATE TABLE  "MOVIELISTS" (
    "MOVIELISTNAME" VARCHAR2(255) NOT NULL PRIMARY KEY,
    "USERNAME" VARCHAR2(255) NOT NULL,
    "MOVIELIST_ID" NUMBER NOT NULL
    
);